### ISSUE TITLE
Add Ability To Map Channel Groups of the Same Type to Each Other

### ISSUE THREAD

**Issue by Beazurt** [TBDFramework/ExecutionInterface#18]
This feature should enable parity with features found in SoftMotion.  SoftMotion has a concept of an Axis which is essentially a collection of tags (position, velocity, limit enable, etc).  These tags get mapped to plug-in hw, but they do so by binding the axis.  Today we could give the same runtime functionality, but the user experience would be slow, confusing, and error prone.  If we supported channel group abstractions and their mapping, we could support the softmotion use-case and any others like it that come up in the future.

**Comment by dsmithni** [comment]
Thinking about it, we should just do a pattern match like <typename>:<instancename>:<elementname> so it'd be "axis:deathmachine:setpt" or perhaps: "axis:setpt:deathmachine" or something like that. Then do a pattern match through a dialog.

**Comment by dsmithni** [comment]
partial implementation in tag editor mapping function. Exec interface is really only responsible for handling the mapping, editor is for making it pretty, so this should be reopened in the editor repo for improvements to that new interface (which absolutely needs improvements)
